sudo: required
dist: trusty
language: minimal
env:
  matrix:
    - ARCH=x86_64
    - ARCH=armhf
    - ARCH=aarch64
    - ARCH=ppc64le
install:
  - sudo ./alpine-chroot-install
script:
  - /alpine/enter-chroot $USER uname -a
  - /alpine/enter-chroot $USER env
